"""
Update theme documents based on latest SKILL.md descriptions.
Updates Function Explanation field with SKILL.md description.
Keeps Why Research-Related field unchanged (already generated by LLM in Phase 2).
For skills from repos that were previously 0 SKILL.md, marks them for LLM review.
"""
import json
import re
from pathlib import Path

BASE_DIR = Path("e:/LLM/EDU+LLM/1/Good_Tools/research-skills")
THEME_DIR = BASE_DIR / "Final_Research_Skills_Thematic_Split"

THEME_FILES = [
    "01_information_retrieval_evidence_collection.md",
    "02_literature_review_writing_citation_part1.md",
    "02_literature_review_writing_citation_part2.md",
    "03_experiment_benchmark_reproducibility_validation_part1.md",
    "03_experiment_benchmark_reproducibility_validation_part2.md",
    "04_data_analysis_and_evidence_interpretation.md",
    "05_research_operations_and_workflow_support.md",
    "06_Additional_Scientific_Skills.md",
]

# Repos that were previously 0 SKILL.md and now have files
NEWLY_AVAILABLE_REPOS = {
    "Shubhamsaboo/awesome-llm-apps",
    "ahmedibrahim085/Claude-Multi-Agent-Research-System-Skill",
    "coffeefuelbump/csv-data-summarizer-claude-skill",
    "danielmiessler/Personal_AI_Infrastructure",
    "HKUDS/DeepCode",
}

def parse_table_row(line):
    """Parse a Markdown table row into columns, handling escaped pipes."""
    if not line.startswith('|'):
        return None
    # Replace escaped pipes with placeholder
    placeholder = '\x00'
    line_esc = line.replace('\\|', placeholder)
    parts = line_esc.split('|')
    # Remove first and last empty parts
    if parts[0] == '':
        parts = parts[1:]
    if parts and parts[-1].strip() == '':
        parts = parts[:-1]
    # Restore escaped pipes
    return [p.strip().replace(placeholder, '\\|') for p in parts]

def extract_evidence_path(col2):
    """Extract evidence file path from backtick-quoted column."""
    match = re.search(r'`([^`]+)`', col2)
    if match:
        return match.group(1)
    return col2.strip()

def truncate_description(desc, max_sentences=3):
    """Truncate description to max_sentences."""
    if not desc:
        return desc
    # Split by sentence endings
    sentences = re.split(r'(?<=[.!?])\s+', desc.strip())
    return ' '.join(sentences[:max_sentences])

def update_theme_document(theme_file, lookup):
    """Update a theme document with latest SKILL.md descriptions."""
    file_path = THEME_DIR / theme_file
    if not file_path.exists():
        print(f"  Warning: {theme_file} not found")
        return 0, 0

    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    updated_lines = []
    current_repo = None
    updated_count = 0
    skipped_count = 0
    is_table_row = False

    for line in lines:
        # Track current repo
        repo_match = re.match(r'^###\s+([^/\s]+/[^/\s]+)', line)
        if repo_match:
            current_repo = repo_match.group(1)
            updated_lines.append(line)
            continue

        # Check if this is a table header or separator
        if re.match(r'^\|[\s-]+\|', line) or re.match(r'^\|\s*Skill\s*\|', line):
            updated_lines.append(line)
            continue

        # Check if this is a table data row
        if line.startswith('|') and current_repo and '|' in line[1:]:
            cols = parse_table_row(line)
            if cols and len(cols) >= 7:
                skill_name = cols[0]
                evidence_path = extract_evidence_path(cols[1])
                skill_url = cols[2]
                why_research = cols[3]
                func_explanation = cols[4]
                exec_flow = cols[5]
                evidence = cols[6]

                # Skip header rows
                if skill_name in ('Skill', '---', ''):
                    updated_lines.append(line)
                    continue

                # Look up in lookup table
                repo_lookup = lookup.get(current_repo, {})
                skill_info = repo_lookup.get(evidence_path)

                if skill_info and skill_info.get('description'):
                    new_func = truncate_description(skill_info['description'], 3)

                    # Only update Function Explanation
                    # Keep Why Research-Related unchanged (already LLM-generated)
                    if new_func and new_func != func_explanation:
                        # Reconstruct the row
                        new_line = f"| {skill_name} | {cols[1]} | {skill_url} | {why_research} | {new_func} | {exec_flow} | {evidence} |\n"
                        updated_lines.append(new_line)
                        updated_count += 1
                        continue
                else:
                    skipped_count += 1

        updated_lines.append(line)

    # Write updated document
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(updated_lines)

    return updated_count, skipped_count

def main():
    print("Updating theme documents with latest SKILL.md descriptions...")
    total_updated = 0
    total_skipped = 0

    for theme_file in THEME_FILES:
        lookup_file = BASE_DIR / theme_file.replace('.md', '_lookup.json')
        if not lookup_file.exists():
            print(f"  Warning: lookup file not found for {theme_file}")
            continue

        with open(lookup_file, 'r', encoding='utf-8') as f:
            lookup = json.load(f)

        print(f"\nProcessing {theme_file}...")
        updated, skipped = update_theme_document(theme_file, lookup)
        print(f"  Updated: {updated} skills, Skipped (no SKILL.md): {skipped} skills")
        total_updated += updated
        total_skipped += skipped

    print(f"\n[DONE] Total updated: {total_updated}, Total skipped: {total_skipped}")

if __name__ == "__main__":
    main()
