"""
/**
 * [IN]  Source markdown files under Final_Research_Skills_Thematic_Split/, plus
 *       inventory JSONL files generated by build_repo_inventory.py.
 * [OUT] Reusable helpers for parsing inventory rows, building output paths,
 *       JSON/JSONL serialization, and Windows long-path-safe filesystem access.
 * [POS] Shared utility module for the repo refresh pipeline scripts; no network
 *       side effects and no direct cutover operations.
 *
 * Change warning: once you modify this file's logic, you must update this comment block,
 * and check/update the module doc (README/CLAUDE) in the containing folder; update the root
 * global map if necessary.
 */
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple
from urllib.parse import unquote

INVENTORY_URL_RE = re.compile(r"^https://github\.com/([^/]+/[^/]+)/blob/([^/]+)/(.+)$")
TABLE_LINK_RE = re.compile(r"\[link\]\((https?://[^)\s]+)\)")
DEFAULT_INCLUDE_REGEX = r"^0[1-6]_.*\.md$"


def normalize_theme_name(file_stem: str) -> str:
    if file_stem.startswith("02_literature_review_writing_citation"):
        return "02_literature_review_writing_citation"
    if file_stem.startswith("03_experiment_benchmark_reproducibility_validation"):
        return "03_experiment_benchmark_reproducibility_validation"
    return file_stem


def normalize_rel_path(path_text: str) -> str:
    value = (path_text or "").strip().strip("`").strip()
    while value.startswith("./"):
        value = value[2:]
    value = value.replace("\\", "/")
    return value


def repo_to_dirname(repo: str) -> str:
    return repo.replace("/", "__")


def fs_path(path: Path) -> str:
    """
    Return an OS string path with Windows long-path prefix when needed.
    """
    resolved = str(path.resolve())
    if os.name != "nt":
        return resolved
    normalized = resolved.replace("/", "\\")
    if normalized.startswith("\\\\?\\"):
        return normalized
    if len(normalized) < 240:
        return normalized
    if normalized.startswith("\\\\"):
        return "\\\\?\\UNC\\" + normalized[2:]
    return "\\\\?\\" + normalized


def path_exists(path: Path) -> bool:
    return os.path.exists(fs_path(path))


def read_bytes(path: Path) -> bytes:
    with open(fs_path(path), "rb") as f:
        return f.read()


def write_bytes(path: Path, content: bytes) -> None:
    os.makedirs(fs_path(path.parent), exist_ok=True)
    with open(fs_path(path), "wb") as f:
        f.write(content)


def write_text(path: Path, text: str) -> None:
    os.makedirs(fs_path(path.parent), exist_ok=True)
    with open(fs_path(path), "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def write_json(path: Path, data: object) -> None:
    write_text(path, json.dumps(data, ensure_ascii=False, indent=2))


def read_json(path: Path) -> object:
    with open(fs_path(path), "r", encoding="utf-8") as f:
        return json.load(f)


def write_jsonl(path: Path, rows: Sequence[Dict[str, object]]) -> None:
    lines = [json.dumps(row, ensure_ascii=False) for row in rows]
    write_text(path, "\n".join(lines) + ("\n" if lines else ""))


def load_jsonl(path: Path) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    with open(fs_path(path), "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if not stripped:
                continue
            rows.append(json.loads(stripped))
    return rows


def collect_source_files(source_dir: Path, include_regex: str) -> List[Path]:
    pattern = re.compile(include_regex)
    files = [
        p for p in source_dir.iterdir()
        if p.is_file() and p.suffix.lower() == ".md" and pattern.match(p.name)
    ]
    return sorted(files, key=lambda p: p.name)


def parse_source_markdown(file_path: Path) -> Tuple[List[Dict[str, object]], List[Dict[str, object]]]:
    rows: List[Dict[str, object]] = []
    issues: List[Dict[str, object]] = []
    theme = normalize_theme_name(file_path.stem)
    current_repo = ""
    lines = file_path.read_text(encoding="utf-8").splitlines()

    for idx, raw in enumerate(lines, start=1):
        line = raw.rstrip("\r")
        if line.startswith("### "):
            current_repo = line[4:].strip()
            continue
        if not line.startswith("|"):
            continue
        if line.startswith("| Skill |") or line.startswith("|---|"):
            continue
        if "[link](" not in line:
            continue

        parts = line.split("|")
        if parts and not parts[0].strip():
            parts = parts[1:]
        if parts and not parts[-1].strip():
            parts = parts[:-1]
        if len(parts) < 7:
            issues.append({
                "type": "parse_error",
                "source_file": file_path.name,
                "line_no": idx,
                "message": "table row has fewer than 7 columns",
            })
            continue
        if len(parts) > 7:
            parts = parts[:6] + ["|".join(parts[6:])]

        skill_name = parts[0].strip().strip("`")
        evidence_file = normalize_rel_path(parts[1])
        link_match = TABLE_LINK_RE.search(parts[2])
        if not link_match:
            issues.append({
                "type": "url_missing",
                "source_file": file_path.name,
                "line_no": idx,
                "message": "missing [link](...) URL in row",
            })
            continue

        skill_url = link_match.group(1)
        url_match = INVENTORY_URL_RE.match(skill_url)
        if not url_match:
            issues.append({
                "type": "url_invalid",
                "source_file": file_path.name,
                "line_no": idx,
                "message": f"URL does not match GitHub blob pattern: {skill_url}",
            })
            continue

        repo_from_url, branch, url_path = url_match.groups()
        url_path = normalize_rel_path(unquote(url_path))
        row_repo = current_repo or repo_from_url
        row_id_seed = f"{theme}|{row_repo}|{skill_name}|{evidence_file}|{file_path.name}|{idx}"
        row_id = hashlib.sha1(row_id_seed.encode("utf-8")).hexdigest()[:16]

        row = {
            "row_id": row_id,
            "theme": theme,
            "source_file": file_path.name,
            "line_no": idx,
            "repo": row_repo,
            "repo_from_url": repo_from_url,
            "branch": branch,
            "skill_name": skill_name,
            "evidence_file": evidence_file,
            "skill_url": skill_url,
            "url_path": url_path,
        }
        rows.append(row)

        if row_repo != repo_from_url:
            issues.append({
                "type": "repo_mismatch",
                "source_file": file_path.name,
                "line_no": idx,
                "row_id": row_id,
                "message": f"header repo '{row_repo}' != url repo '{repo_from_url}'",
            })
        if evidence_file != url_path:
            issues.append({
                "type": "path_mismatch",
                "source_file": file_path.name,
                "line_no": idx,
                "row_id": row_id,
                "message": f"evidence_file '{evidence_file}' != url path '{url_path}'",
            })

    return rows, issues


def build_inventory(source_dir: Path, include_regex: str) -> Tuple[List[Dict[str, object]], List[Dict[str, object]]]:
    files = collect_source_files(source_dir, include_regex)
    all_rows: List[Dict[str, object]] = []
    issues: List[Dict[str, object]] = []
    for file_path in files:
        rows, file_issues = parse_source_markdown(file_path)
        all_rows.extend(rows)
        issues.extend(file_issues)
    return all_rows, issues


def build_repo_summary(rows: Sequence[Dict[str, object]], include_regex: str, source_dir: Path) -> Dict[str, object]:
    per_theme = Counter()
    per_repo = Counter()
    repo_branches: Dict[str, set] = defaultdict(set)
    source_files = sorted({str(r["source_file"]) for r in rows})
    for row in rows:
        per_theme[str(row["theme"])] += 1
        repo = str(row["repo"])
        per_repo[repo] += 1
        repo_branches[repo].add(str(row["branch"]))
    repos = sorted(per_repo.keys())

    return {
        "source_dir": str(source_dir),
        "include_regex": include_regex,
        "source_files": source_files,
        "rows_count": len(rows),
        "unique_repo_count": len(repos),
        "theme_counts": dict(sorted(per_theme.items())),
        "repo_counts": {repo: per_repo[repo] for repo in repos},
        "repo_branches": {repo: sorted(repo_branches[repo]) for repo in repos},
        "repos": repos,
    }


def repo_jobs_from_inventory(rows: Sequence[Dict[str, object]]) -> Dict[str, Dict[str, object]]:
    jobs: Dict[str, Dict[str, object]] = {}
    for row in rows:
        repo = str(row.get("repo_from_url") or row["repo"])
        branch = str(row["branch"])
        job = jobs.setdefault(repo, {
            "repo": repo,
            "repo_url": f"https://github.com/{repo}.git",
            "branches": set(),
        })
        job["branches"].add(branch)
    normalized = {}
    for repo, job in jobs.items():
        normalized[repo] = {
            "repo": repo,
            "repo_url": job["repo_url"],
            "branches": sorted(job["branches"]),
        }
    return normalized


def build_output_relative_path(row: Dict[str, object]) -> Path:
    repo = str(row["repo"])
    theme = str(row["theme"])
    evidence = str(row["evidence_file"])
    parts = [p for p in evidence.split("/") if p]
    return (
        Path("Final_Research_Skills_Link_Downloads_By_Theme_LATEST")
        / theme
        / repo_to_dirname(repo)
        / Path(*parts)
    )


def sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()
